-- AlterTable
ALTER TABLE "Godown" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "InvoiceBook" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "JournalEntry" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
